/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ascensor_poo;

/**
 *
 * @author lopez
 */
public class AcscensorVisual extends javax.swing.JFrame {

    /**
     * Creates new form AcscensorVisual
     */
    Cabina c1;
    Acscensor A1;

    public AcscensorVisual() {
        initComponents();
        this.txtpiso.setText("PB");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnp2 = new javax.swing.JButton();
        btnp8 = new javax.swing.JButton();
        btnp5 = new javax.swing.JButton();
        btnp6 = new javax.swing.JButton();
        btnp3 = new javax.swing.JButton();
        btnp4 = new javax.swing.JButton();
        btnp7 = new javax.swing.JButton();
        btnp10 = new javax.swing.JButton();
        btnp9 = new javax.swing.JButton();
        btnp12 = new javax.swing.JButton();
        btnp11 = new javax.swing.JButton();
        btnp16 = new javax.swing.JButton();
        btnp13 = new javax.swing.JButton();
        btnpb = new javax.swing.JButton();
        btnp14 = new javax.swing.JButton();
        btnp15 = new javax.swing.JButton();
        txtestado = new javax.swing.JTextField();
        txtpiso = new javax.swing.JTextField();
        txtpersonas = new javax.swing.JTextField();
        txttamaño = new javax.swing.JTextField();
        lblm2 = new javax.swing.JLabel();
        lblpersonas = new javax.swing.JLabel();
        lbltamaño = new javax.swing.JLabel();
        btnp = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnp2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp2.setText("2");
        btnp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp2ActionPerformed(evt);
            }
        });

        btnp8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp8.setText("8");
        btnp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp8ActionPerformed(evt);
            }
        });

        btnp5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp5.setText("5");
        btnp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp5ActionPerformed(evt);
            }
        });

        btnp6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp6.setText("6");
        btnp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp6ActionPerformed(evt);
            }
        });

        btnp3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp3.setText("3");
        btnp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp3ActionPerformed(evt);
            }
        });

        btnp4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp4.setText("4");
        btnp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp4ActionPerformed(evt);
            }
        });

        btnp7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp7.setText("7");
        btnp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp7ActionPerformed(evt);
            }
        });

        btnp10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp10.setText("10");
        btnp10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp10ActionPerformed(evt);
            }
        });

        btnp9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp9.setText("9");
        btnp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp9ActionPerformed(evt);
            }
        });

        btnp12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp12.setText("12");
        btnp12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp12ActionPerformed(evt);
            }
        });

        btnp11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp11.setText("11");
        btnp11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp11ActionPerformed(evt);
            }
        });

        btnp16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp16.setText("16");
        btnp16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp16ActionPerformed(evt);
            }
        });

        btnp13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp13.setText("13");
        btnp13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp13ActionPerformed(evt);
            }
        });

        btnpb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnpb.setText("PB");
        btnpb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpbActionPerformed(evt);
            }
        });

        btnp14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp14.setText("14");
        btnp14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp14ActionPerformed(evt);
            }
        });

        btnp15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp15.setText("15");
        btnp15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnp15ActionPerformed(evt);
            }
        });

        txtestado.setEditable(false);
        txtestado.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        txtestado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtpiso.setEditable(false);
        txtpiso.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        txtpiso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpisoActionPerformed(evt);
            }
        });

        txtpersonas.setText("0");
        txtpersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonasActionPerformed(evt);
            }
        });

        txttamaño.setText("1");

        lblm2.setText("M^2");

        lblpersonas.setText("Nro de Personas:");

        lbltamaño.setText("Tamaño Cabina:");

        btnp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnp.setText("1");
        btnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbltamaño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblpersonas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttamaño, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblm2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpiso)
                    .addComponent(txtestado))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnp3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnpb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnp10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnp11)
                            .addComponent(btnp14, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnp15)
                            .addComponent(btnp12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnp13)
                            .addComponent(btnp16)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnp7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnp8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnp9))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(btnp4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnp5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnp6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpiso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnp16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnp13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnp14)
                            .addComponent(btnp15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnp12)
                            .addComponent(btnp11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnp10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnp9)
                    .addComponent(btnp8)
                    .addComponent(btnp7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnp6)
                    .addComponent(btnp5)
                    .addComponent(btnp4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnp2)
                    .addComponent(btnp3)
                    .addComponent(btnp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpersonas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblm2)
                    .addComponent(lbltamaño))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp2ActionPerformed
        CrearAcesnsor();

        if (this.txtpiso.getText().equals("PB")) {

            A1.Subir(2);
            if (A1.ComprobacionDeCapacidad() == false) {
                this.txtestado.setText("!ERROR!");
                this.txtpiso.setText(A1.Imprimir());
            } else {
                Subiendo();
                this.txtpiso.setText(A1.Imprimir());
            }

        } else if (Integer.parseInt(this.txtpiso.getText()) > 2) {
            for (int i = Integer.parseInt(this.txtpiso.getText()); i >= 0; i--) {
                A1.Bajar();
                this.txtpiso.setText(i + "");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnp2ActionPerformed

    private void btnp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp8ActionPerformed

    private void btnp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp5ActionPerformed

    private void btnp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp6ActionPerformed

    private void btnp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp3ActionPerformed

    private void btnp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp4ActionPerformed

    private void btnp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp7ActionPerformed

    private void btnp10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp10ActionPerformed

    private void btnp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp9ActionPerformed

    private void btnp12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp12ActionPerformed

    private void btnp11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp11ActionPerformed

    private void btnp16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp16ActionPerformed

    private void btnp13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp13ActionPerformed

    private void btnpbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpbActionPerformed
        CrearAcesnsor();
        if (A1.getPisoActual() != 0) {
            if (A1.ComprobacionDeCapacidad() == false) {
                this.txtestado.setText("!ERROR!");
                this.txtpiso.setText(A1.Imprimir());
            } else {
                for (int i = Integer.parseInt(this.txtpiso.getText()); i >= 0; i--) {
                    A1.Bajar();
                    this.txtpiso.setText(i + "");
                }
            }

        }

    }//GEN-LAST:event_btnpbActionPerformed

    private void btnp14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp14ActionPerformed

    private void btnp15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnp15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnp15ActionPerformed

    private void txtpisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpisoActionPerformed

    private void txtpersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonasActionPerformed

    private void btnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpActionPerformed
        CrearAcesnsor();

        if (A1.getPisoActual() !=0) {
            A1.Bajar();
            if (A1.ComprobacionDeCapacidad() == false) {
                this.txtestado.setText("!ERROR!");
                this.txtpiso.setText(A1.Imprimir());
            } else {
                Bajando();
                for (int i = Integer.parseInt(this.txtpiso.getText()); i >= 0; i--) {

                    this.txtpiso.setText(i + "");
                }
            }

        } else {

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcscensorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcscensorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcscensorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcscensorVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcscensorVisual().setVisible(true);
            }
        });
    }

    public void CrearAcesnsor() {

        if (A1 == null && c1 == null) {
            c1 = new Cabina(Integer.parseInt(this.txttamaño.getText()));
            A1 = new Acscensor(c1, 15, Integer.parseInt(this.txtpersonas.getText()));
        } else {
            c1.setTamañoX(Integer.parseInt(this.txttamaño.getText()));
            c1.setTamañoY(Integer.parseInt(this.txttamaño.getText()));
            A1.setCabina(c1);
            A1.setNroDePersonas(Integer.parseInt(this.txtpersonas.getText()));

        }
    }

    public void Subiendo() {

        new Thread(() -> {
            try {
                txtestado.setText("Subiendo.");
                Thread.sleep(250);

                txtestado.setText("Subiendo..");
                Thread.sleep(250);

                txtestado.setText("Subiendo...");
                Thread.sleep(250);

                txtestado.setText("Subiendo....");
                Thread.sleep(250);

                txtestado.setText("!Listo!");
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();

    }

    public void Bajando() {

        new Thread(() -> {
            try {
                txtestado.setText("Bajando.");
                Thread.sleep(250);

                txtestado.setText("Bajando..");
                Thread.sleep(250);

                txtestado.setText("Bajando...");
                Thread.sleep(250);

                txtestado.setText("Bajando....");
                Thread.sleep(250);

                txtestado.setText("!Listo!");
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnp;
    private javax.swing.JButton btnp10;
    private javax.swing.JButton btnp11;
    private javax.swing.JButton btnp12;
    private javax.swing.JButton btnp13;
    private javax.swing.JButton btnp14;
    private javax.swing.JButton btnp15;
    private javax.swing.JButton btnp16;
    private javax.swing.JButton btnp2;
    private javax.swing.JButton btnp3;
    private javax.swing.JButton btnp4;
    private javax.swing.JButton btnp5;
    private javax.swing.JButton btnp6;
    private javax.swing.JButton btnp7;
    private javax.swing.JButton btnp8;
    private javax.swing.JButton btnp9;
    private javax.swing.JButton btnpb;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblm2;
    private javax.swing.JLabel lblpersonas;
    private javax.swing.JLabel lbltamaño;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtpersonas;
    private javax.swing.JTextField txtpiso;
    private javax.swing.JTextField txttamaño;
    // End of variables declaration//GEN-END:variables

}
