/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuadrado.majico;

import java.awt.Font;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author lopez
 */
public class Cuadrado_visual_ extends javax.swing.JFrame {

    /**
     * Creates new form Cuadrado_visual_
     */
    private JTextField[][] Cuadrado;
    private int tamaño;
    private int col;
    private int fil;
    private int cont;


    public Cuadrado_visual_() {
        initComponents();
        cbvelocidad.setSelectedIndex(4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        cbvelocidad = new javax.swing.JComboBox<>();
        btnEjecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setName(""); // NOI18N

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabel1.setText("Cuadrado Magico");

        jLabel2.setText("Tamaño:");

        txtTamaño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTamaño.setText("1");
        txtTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamañoActionPerformed(evt);
            }
        });

        cbvelocidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x2", "x1.75", "x1.5", "x1.25", "Normal", "x0.75", "x0.5", "x0.25", " " }));
        cbvelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbvelocidadActionPerformed(evt);
            }
        });

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(cbvelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addComponent(btnEjecutar)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbvelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjecutar))
                .addGap(23, 23, 23)
                .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamañoActionPerformed

    private void cbvelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbvelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbvelocidadActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        this.Panel1.removeAll();

        tamaño = Integer.parseInt(this.txtTamaño.getText());
        if (tamaño % 2 == 0) {
            tamaño++;
        }
        Cuadrado = new javax.swing.JTextField[tamaño][tamaño];
        int x;
        int y;
        y = 0;
        x = 0;
        for (int i = 0; i < Cuadrado.length; i++) {
            for (int j = 0; j < Cuadrado.length; j++) {
                Cuadrado[i][j] = new JTextField();
                Cuadrado[i][j].setBounds(10 + x, 10 + y, 40, 40);
                Cuadrado[i][j].setHorizontalAlignment(JTextField.CENTER);
                Cuadrado[i][j].setFont(new Font("SansSerif", Font.PLAIN, 9));
                Cuadrado[i][j].setEditable(false);
                this.Panel1.add(Cuadrado[i][j]);
                x += 40;
            }
            y += 40;
            x = 0;
        }

      this.col = tamaño / 2;
        this.fil = 0;
        this.cont = 1;
//              
        int delay = Descanso();
        Timer timer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Cuadrado[fil][col].setText(cont +"");
                cont++;

                int filA = fil;
                int colA = col;
                if (fil == 0) {
                    fil = tamaño - 1;
                } else {
                    fil--;
                }

                if (col == tamaño - 1) {
                    col = 0;
                } else {
                    col++;
                }

                if (!Cuadrado[fil][col].getText().equals("")) {
                    fil = filA + 1;
                    col = colA;
                }

                if (cont > tamaño * tamaño) {
                    ((Timer) e.getSource()).stop();
                }
            }
        });

        timer.start();

        this.Panel1.revalidate();
        this.Panel1.repaint();


    }//GEN-LAST:event_btnEjecutarActionPerformed
    public int Descanso() {
        if (this.cbvelocidad.getSelectedIndex() == 0) {
            return 0;
        } else if (this.cbvelocidad.getSelectedIndex() == 1) {
            return 100;
        } else if (this.cbvelocidad.getSelectedIndex() == 2) {
            return 500;
        } else if (this.cbvelocidad.getSelectedIndex() == 3) {
            return 2000;
        } else if (this.cbvelocidad.getSelectedIndex() == 5) {
            return 2000;

        } else if (this.cbvelocidad.getSelectedIndex() == 6) {
            return 3000;
        } else if (this.cbvelocidad.getSelectedIndex() == 7) {
            return 4000;
        } else {
            return 1000;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuadrado_visual_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuadrado_visual_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuadrado_visual_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuadrado_visual_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuadrado_visual_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JComboBox<String> cbvelocidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables

}
